### ISSUE TITLE
switch case 控制流平坦化 反混淆，感觉没什么变化

### ISSUE THREAD

**Issue by L018** [virjar/geeEtacsufbo#3]
老哥 这个 geetest.6.0.9.js 和 geetest.6.0.9_beauty.json，switch case 这一块感觉没有什么变化，这块有什么好的解决办法吗？

**Comment by leveryd** [comment]
同感，变化不大

**Comment by virjar** [comment]
那一定是你感觉错了。控制流有明显的变化。附件中的ppt有摘抄控制流去除前后的代码片段。有疑问的自行看ppt
